server:
  servlet:
    context-path: /portal-service
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sevensense?currentSchema=portal
    username: postgres
    password: sevensensedb
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog.yaml
    enabled: true
auth:
  jwt:
    jwtSecret: xazxlfg2
    jwtExpirationMs: 86400000
api:
  base-url: http://localhost:8080
